apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: services-endpoints-lister
  namespace: lab3
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - list
  - get
