apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-endpoint
  namespace: lab3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: services-endpoints-lister
